### ISSUE TITLE
Dotnet SDK path mismatch to VSCode suggested location

### ISSUE THREAD

**Issue by seantleonard** [Azure-Samples/azure-sql-library-app-blazor#13]
https://github.com/Azure-Samples/azure-sql-library-app-blazor/blob/20dcf6858a7ccbba15dbed17769df754823052b1/.devcontainer/devcontainer.json#L27

VSCode suggests that the path be: `/usr/share/dotnet` and not include the `sdk` folder, since there doesn't seem to be a `dotnet.exe` in the `sdk` folder.

![image](https://github.com/Azure-Samples/azure-sql-library-app-blazor/assets/6414189/20c6dc5b-7783-49a6-b212-2fc3983f8941)

![image](https://github.com/Azure-Samples/azure-sql-library-app-blazor/assets/6414189/d2f6bd5c-8400-44dc-8595-2c25e5071e84)

**Comment by seantleonard** [comment]
This affect building the Blazor project

**Comment by croblesm** [comment]
Thanks, this issue was fixed under commit: fb0b7530251e42da4a6455317bf8f1377fc1c31c

**Comment by seantleonard** [comment]
Hey @croblesm , this issue is opened up on the latest code you merged in this commit https://github.com/Azure-Samples/azure-sql-library-app-blazor/commit/20dcf6858a7ccbba15dbed17769df754823052b1. 

The path doesn't align with suggestion by VSCode.

**Comment by seantleonard** [comment]
Can you reopen?

**Comment by croblesm** [comment]
Hi @seantleonard,

Could you please try building / publishing the Database project using this configuration? I'm using this path in multiple dev containers and the build/publish works just fine whether I do it from command line or the UI.

**Comment by croblesm** [comment]
Using command line
![Screenshot 2024-06-27 at 8 36 33 PM](https://github.com/Azure-Samples/azure-sql-library-app-blazor/assets/38668645/08f2b05e-4b2e-4893-aee9-bbc683950538)

**Comment by croblesm** [comment]
using UI
![Screenshot 2024-06-27 at 8 36 55 PM](https://github.com/Azure-Samples/azure-sql-library-app-blazor/assets/38668645/a04e61db-2704-4a2d-9174-72f6d56eed40)

Build
![Screenshot 2024-06-27 at 8 37 11 PM](https://github.com/Azure-Samples/azure-sql-library-app-blazor/assets/38668645/5251845a-049f-42b8-9186-965a4fd5a898)

Publish
![Screenshot 2024-06-27 at 8 37 56 PM](https://github.com/Azure-Samples/azure-sql-library-app-blazor/assets/38668645/83866b0a-248c-4f2f-bff3-a80814784fc2)
