### ISSUE TITLE
README sample sa password is wrong

### ISSUE THREAD

**Issue by seantleonard** [Azure-Samples/azure-sql-library-app-blazor#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: 

- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

In the repo root's Readme, the following paragraph references an incorrect sa password

> The SQL container runs on the latest developer edition of Microsoft SQL 2022. Within VS Code, databases are conveniently accessible through the MSSQL extension, labeled "LocalDev". The default sa user password is P@ssw0rd!, and SQL port 1433 is the default, as defined in .devcontainer/docker-compose.yml. Additionally, database setup occurs when the Dev Container is started, employing the .devcontainer/sql/postCreateCommand.sh file. The .devcontainer/sql/library.azure-sql.sql script is utilized to create the library database and its objects. Moreover, a SQL Database project is included, offering the means to locally update the database. Pre and post scripts ensure the utilization of static data for demo purposes.

The password is `P@ssw0rd` and not `P@ssw0rd!` (no exclamation mark.

https://github.com/Azure-Samples/azure-sql-library-app-blazor/blob/0a1ba8c97744d887f209d95c7f932ddf0eb8b04c/README.md?plain=1#L78

Correct password referenced from the remote try sql server sample: https://github.com/microsoft/vscode-remote-try-sqlserver

**Comment by seantleonard** [comment]
this may not be an issue because this specific sample uses the password mentioned, but I opened #6 because the directions have me deploy a different sample which has a different password. Confusing.

**Comment by croblesm** [comment]
Thanks for reporting this issue, it was fixed under this commit: 06ff3078ffe49284f0d95fdcc66fcd6b20f5e994
